services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: PostgreSQL 14
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

    pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
        PGADMIN_CONFIG_SERVER_MODE: 'False'
      volumes:
        - pgadmin:var/lib/pgadmin
      ports:
        - "5050:80"
      networks:
        - postgres
      restart: unless-stopped

  network:
    postgres:
      driver: bridge

  volumes:
    postgres:
    pgadmin:
